# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Kijoong kim
paginate:       5
baseurl:        ""
url:            "https://kimkijoong.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         kijoong kim
  url:          http://kimkijoong.github.io
  email:        kkj6943@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/kimkijoong

# Gems
plugins:
  - jekyll-paginate
